-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgefijh9taDaebymil
2doSuRa5DBk3qNAjL++4rwyC6Q2gCgYIKoZIzj0DAQehRANCAATLaBKdhu0hzdUT
FPJCmFzylF2zJyWkmLS+XUGa++89F2qaA26RfKJsxKJdceRATnoPNilNzHCH7roC
RO0hdV/W
-----END PRIVATE KEY-----